RoasManager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic import TemplateView
from roas_manager.views import *
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls, name="api"),
    path('api/', include('roas_manager.urls')),
    path('', DayOverview.as_view(), name="overview"),
    path('strategies/', Strategies.as_view(), name="strategies"),
    path('google-ads-accounts/', ViewAccounts.as_view(), name="accounts"),
    path('google-ads-accounts/add-account/', AddAccount.as_view(), name="add_account"),
    path('edit-account/<int:pk>/', EditAccount.as_view(), name="edit_account"),
    path('google-ads-accounts/add-campaign-group/', AddCampaignGroup.as_view(), name="add_campaign_group"),
    path('campaign-group/<int:pk>/', EditCampaignGroup.as_view(), name="edit_campaign_group"),
    path('strategy/<int:strategy_id>/edit/', StrategyView.as_view(), name="strategy"),
    path('strategy/<int:strategy_id>/', ViewLog.as_view(), name="log"),
    path('strategy/add/', AddStrategy.as_view(), name="add_strategy"),
    path('get-performance/', CampaignGroupsPerformance.as_view(), name="get_report"),
    path('update-strategy-roas/', SetStrategyRoas.as_view(), name="set_strategy_roas"),
    path('update-campaign-roas/', SetCampaignRoas.as_view(), name="set_campaign_roas"),
    path('campaign_group/<int:campaign_group_id>/add-budget/', AddBudget.as_view(), name="add_budget"),
    path('campaign_group/<int:campaign_group_id>/edit-budget/<int:pk>', EditBudget.as_view(), name="edit_budget"),
    path('verify-budgets/', VerifyBudgetView.as_view(), name="verify_budget"),
    path('update-url-suffix/', SetUrlSuffix.as_view(), name="update_suffix"),
    path('settings/', SettingsPage.as_view(), name="settings"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('campaigns/', CampaignsView.as_view(), name="campaigns"),
    path('campaign/<int:pk>', CampaignEditView.as_view(), name="campaign"),
    path('campaigns/add-campaign/', AddCampaignView.as_view(), name="add_campaign"),
    path('error', ErrorView.as_view(), name="error"),
    path('report/campaign-groups/', CampaignGroupsReportView.as_view(), name="custom_cg_report"),
    path('alerts-settings/<int:pk>/', AlertsSettingsView.as_view(), name="alerts_settings"),
    path('alerts/', AlertsView.as_view(), name="alerts"),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

roas_manager/forms.py
from django import forms
from .models import *


class BaseForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class BudgetForm(BaseForm):
    to_spend = forms.DecimalField(label='Kwota budżetu', decimal_places=2)
    date_from = forms.DateField(label='Początek')
    date_to = forms.DateField(label='Koniec')


class GetCostClicksForm(forms.Form):
    accounts = Account.objects.all()
    campaign_groups = CampaignGroup.objects.all()
    account = forms.ModelChoiceField(label='Konto', queryset=accounts)
    campaign_group = forms.ModelMultipleChoiceField(queryset=campaign_groups,
                                                    widget=forms.CheckboxSelectMultiple(attrs={'checked': 'checked'}),
                                                    label="Grupy kampanii do aktualizacji")
    date_from = forms.DateField(label='Pobierz dane od dnia:')
    date_to = forms.DateField(label='do dnia:')


class AccountForm(BaseForm):
    campaign_group_id = forms.CharField(disabled=True)
    account_name = forms.CharField(label='Nazwa konta')
    account_name.widget.attrs['size'] = '50'
    account_number = forms.CharField(label='Numer konta')
    users = CustomUser.objects.all()
    user = forms.ModelMultipleChoiceField(label='Właściciel', queryset=users, widget=forms.CheckboxSelectMultiple)


class CampaignGroupForm(forms.ModelForm):
    class Meta:
        model = CampaignGroup
        fields = '__all__'
    campaign_group_id = forms.CharField(disabled=True)


class SetRoasForm(forms.Form):
    accounts = Account.objects.all()
    account = forms.ModelChoiceField(label='Konto', queryset=accounts)
    account.widget.attrs['class'] = 'form-control'
    campaign_groups = CampaignGroup.objects.all()
    campaign_group = forms.ModelMultipleChoiceField(queryset=campaign_groups,
                                                    widget=forms.CheckboxSelectMultiple(),
                                                    label="Nadrzędne grupy kampanii:")
    campaign_group.widget.attrs['class'] = "form-check-input"
    strategies = Strategy.objects.all()
    strategy = forms.ModelMultipleChoiceField(queryset=strategies, widget=forms.CheckboxSelectMultiple(),
                                              label="Strategie źródłowe:")
    strategy.widget.attrs['class'] = "form-check-input"
    override_check = forms.BooleanField(label="Pomiń elementy, których tROAS był już dziś aktualizowany")
    override_check.initial = True
    override_check.required = False


class StrategyForm(forms.Form):
    name = forms.CharField(label='Nazwa strategii:')
    name.widget.attrs['class'] = 'form-control'
    name.widget.attrs['size'] = '50'
    accounts = Account.objects.all()
    account = forms.ModelChoiceField(label='Konto:', queryset=accounts)
    account.widget.attrs['class'] = 'form-control'
    # account.disabled = True
    campaign_groups = CampaignGroup.objects.all()
    campaign_group = forms.ModelChoiceField(label='Grupa kampanii:', queryset=campaign_groups)
    campaign_group.widget.attrs['class'] = 'form-control'
    make_changes = forms.BooleanField(label='Zarządzanie budżetem:')
    make_changes.widget.attrs['class'] = "custom-control-input"
    make_changes.required = False
    strategy_id = forms.IntegerField(label='Nr ID strategii:')
    strategy_id.widget.attrs['class'] = 'form-control'
    strategy_id.disabled = True


class GlobalSettingsForm(BaseForm):
    tax = forms.DecimalField(label='Podatek (mnożnik):', decimal_places=2)
    return_rate = forms.DecimalField(label='Wysokość zwrotów (mnożnik):', decimal_places=2)


class CampaignForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CampaignForm, self).__init__(*args, **kwargs)
        self.fields['type'].disabled = True
        self.fields['campaign_id'].disabled = True

    class Meta:
        model = Campaign
        fields = '__all__'

templates/__base__.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>{% block title %}{% endblock title %}</title>

    <link rel=icon href={% static 'img/favicon.ico' %}>
    <!-- Bootstrap -->
    {#<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">#}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker3.standalone.min.css' %}">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
</head>
<body>
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'overview' %}">ROAS Manager</a>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="{% url 'logout' %}" id="user_logged" data-user="{{ request.user.id }}">Wyloguj</a>
        </li>
    </ul>
</nav>

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>ROAS Manager</span>
                    <a class="d-flex align-items-center text-muted" href="#">
                        <span data-feather="plus-circle"></span>
                    </a>
                </h6>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'overview' %}">
                            <span data-feather="minimize"></span>
                            Podsumowanie dzienne
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'strategies' %}">
                            <span data-feather="trending-up"></span>
                            Strategie
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'campaigns' %}">
                            <span data-feather="bar-chart-2"></span>
                            Kampanie
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts' %}">
                            <span data-feather="database"></span>
                            Konta i grupy kampanii
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'verify_budget' %}">
                            <span data-feather="dollar-sign"></span>
                            Weryfikacja budżetów
                            {% if not unverified_budgets_number == 0 %}
                                <span class="badge badge-warning">{{ unverified_budgets_number }}</span>
                            {% endif %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'get_report' %}">
                            <span data-feather="download"></span>
                            Uzupełnij dane
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'set_strategy_roas' %}">
                            <span data-feather="play"></span>
                            Aktualizuj tROAS w strategiach
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'set_campaign_roas' %}">
                            <span data-feather="skip-forward"></span>
                            Aktualizuj tROAS w kampaniach
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'alerts' %}">
                            <span data-feather="bell"></span>
                            Powiadomienia
                            {% if not alerts_number == 0 %}
                                <span class="badge badge-danger">{{ alerts_number }}</span>
                            {% endif %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'settings' %}">
                            <span data-feather="settings"></span>
                            Ustawienia
                        </a>
                    </li>
                </ul>

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>Uzupełnij sufiksy adresu końcowego</span>
                    <a class="d-flex align-items-center text-muted" href="#">
                        <span data-feather="plus-circle"></span>
                    </a>
                </h6>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'update_suffix' %}">
                            <span data-feather="layers"></span>
                            Dodawanie sufiksów
                        </a>
                    </li>
                </ul>

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>Raporty Google Sheets</span>
                    <a class="d-flex align-items-center text-muted" href="#">
                        <span data-feather="plus-circle"></span>
                    </a>
                </h6>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'custom_cg_report' %}">
                            <span data-feather="grid"></span>
                            Raport grup kampanii
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            <div class="row">
                <div class="col-sm"></div>
                <div class="col-sm"></div>
                <div class="col-sm"></div>
            </div>

            <!-- //--------------------------- page content -------------------------// -->
            {% block content %}{% endblock content %}
            <!-- //--------------------------- page content end ---------------------// -->

        </main>
    </div>
</div>

{#    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>#}
{#<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>#}
{#    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>#}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>#}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>#}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/jquery-3.4.1.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/feather.min.js' %}"></script>
<script src="{% static 'js/dashboard.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>

{% block switch_ajax %}{% endblock switch_ajax %}
{% block switch_campaigns_ajax %}{% endblock switch_campaigns_ajax %}
{% block save_campaign_group_ajax %}{% endblock save_campaign_group_ajax %}
{% block save_strategy_ajax %}{% endblock save_strategy_ajax %}
{% block save_campaign_ajax %}{% endblock save_campaign_ajax %}
{% block hide_checkboxes_js %}{% endblock hide_checkboxes_js %}
{% block verify_budget %}{% endblock verify_budget %}
{% block date_picker_range %}{% endblock date_picker_range %}
{% block date_picker %}{% endblock date_picker %}
{% block filter_alerts %}{% endblock filter_alerts %}

</body>
</html>

templates/accounts.html
{% extends "__base__.html" %}
{% block title %}ROAS Manager | Konta i grupy kampanii{% endblock %}
{% block content %}

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1>Konta i grupy kampanii Google Ads</h1>

            <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group mr-2">
                <a href="{% url 'add_campaign_group' %}">
                    <button type="button" class="btn btn-sm btn-outline-secondary" id="all-items">
                        <span data-feather="plus-circle"></span>
                        Dodaj grupę kampanii
                    </button>
                </a>
            </div>
            <div class="btn-group mr-2">
                <a href="{% url 'add_account' %}">
                    <button type="button" class="btn btn-sm btn-outline-secondary" id="all-items">
                        <span data-feather="plus-circle"></span>
                        Dodaj konto Google Ads
                    </button>
                </a>
            </div>
        </div>
    </div>

    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'strategies' %}">Strona główna</a></li>
        <li class="breadcrumb-item active" aria-current="page">Konta i grupy kampanii</li>
      </ol>
    </nav>


    <div class="row">
        <div class="col-sm">
            <h3>Grupy kampanii</h3>
            <div class="table">
                <table class="table table-striped table-bordered table-sm">
                <tr>
                    <th>Nazwa</th>
                    <th>Konto</th>
                </tr>
                {% for campaign_group in campaign_groups %}
                <tr>
                    <td><a href="{% url 'edit_campaign_group' campaign_group.id %}">{{ campaign_group.name }}</a></td>
                    <td>{{ campaign_group.account.account_name }}</td>
                </tr>
                {% endfor %}
                </table>
            </div>
            <a class="align-items-center" href="{% url 'add_campaign_group' %}"><span data-feather="plus-circle"></span>  Dodaj grupę kampanii</a>
        </div>
        <div class="col-sm">
            <h3>Konta Google Ads</h3>
            <div class="table">
                <table class="table table-striped table-bordered table-sm">
                <tr>
                    <th>Nazwa konta</th>
                    <th>Numer konta</th>
                </tr>
                {% for account in accounts %}
                <tr>
                    <td><a href="{% url 'edit_account' account.id %}">{{ account.account_name }}</a></td>
                    <td>{{ account.account_number }}</td>
                </tr>
                {% endfor %}
                </table>
            </div>
            <a class="align-items-center" href="{% url 'add_account' %}"><span data-feather="plus-circle"></span>  Dodaj konto</a>

        </div>
    </div>
{% endblock %}

templates/alerts.html
{% extends "__base__.html" %}
{% block title %}ROAS Manager | Alerty{% endblock %}
{% block content %}
    {% load crispy_forms_tags %}
    {% load static %}


    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1>Powiadomienia</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group mr-2">
                <button role="button" class="btn btn-sm btn-outline-secondary dropdown-toggle" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span data-feather="calendar"></span>
                    {% if not date %}
                        {{ today }}
                    {% else %}
                        {{ date }}
                    {% endif %}
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" id="date"></div>
            </div>
            <div class="btn-group mr-2">
                <button type="button" class="btn btn-sm btn-outline-secondary" id="user-items">Moje powiadomienia</button>
            </div>
            <div class="btn-group mr-2">
                <button type="button" class="btn btn-sm btn-outline-secondary" id="all-items">Wszystkie powiadomienia</button>
            </div>
            <form style="display: none" method="post" action="#" id="switch-budget">
                {% csrf_token %}
                <input type="text" name="date_from" class="form-control dateinput form-control" id="budget_date">
                <input type="submit" value="przełącz budżet">
            </form>
        </div>
    </div>

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'strategies' %}">Strona główna</a></li>
            <li class="breadcrumb-item active" aria-current="page">Powiadomienia</li>
        </ol>
    </nav>

    <h3>Powiadomienia na dzień {% if date %}{{ date }}{% else %}{{ today }}{% endif %}.</h3>
    {% if alerts %}
    <p>Twoje powiadomienia to <b>{{ user_alerts_count }}</b> z <b>{{ all_alerts_count }}</b> powiadomień na ten dzień.
        {% if user_alerts_count != all_alerts_count %}
    Kliknij "Wszystkie powiadomienia", aby zobaczyć pozostałe.</p>
        {% endif %}
    {% endif %}
    <div class="row">
        <div class="col-sm">

        {% if alerts %}
            {% for alert in alerts %}
                <div class="alert alert-danger dynamic-div" role="alert" data-user="{% for user in alert.user.all %}{{ user.id }},{% endfor %}">
                    {{ alert.message }}
                </div>
            {% endfor %}

            {% else %}
                {% if date %}
                <p>Brak powiadomień na dzień {{ date }}.</p>
                {% else %}
                <p>Brak powiadomień na dzień {{ today }}.</p>
            {% endif %}
        {% endif %}

        </div>
    </div>

{% endblock %}
{% block date_picker %}
    <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.pl.min.js' %}"></script>
    <script src="{% static 'js/log_switch_budget.js' %}"></script>
{% endblock date_picker %}
{% block filter_alerts %}
    <script src="{% static 'js/filter_alerts.js' %}"></script>
{% endblock %}

templates/error.html
{% extends "__base__.html" %}
{% block title %}ROAS Manager | Błąd{% endblock %}
{% block content %}
    {% load crispy_forms_tags %}


    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1>Błąd API</h1>
    </div>

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'strategies' %}">Strona główna</a></li>
            <li class="breadcrumb-item active" aria-current="page">Błąd</li>
        </ol>
    </nav>

    <div class="row">
        <div class="col-sm">
            <p>Wystąpił błąd podczas pobierania danych przez API, powiadom administratora.</p>
        </div>
    </div>

{% endblock %}

templates/set_suffix.html
{% extends "__base__.html" %}
{% block title %}ROAS Manager | Uzupełnij sufiksy końcowego adresu URL{% endblock %}
{% block content %}
{% load crispy_forms_tags %}

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1>Uzupełnij sufiksy końcowego adresu URL na kontach Google Ads</h1>
    </div>

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'strategies' %}">Strona główna</a></li>
            <li class="breadcrumb-item active" aria-current="page">Dodawanie sufiksów</li>
        </ol>
    </nav>

            <p>Sufiksy końcowego adresu URL uzupełniane są wyłącznie na poziomie grup reklam, gdzie ich brakuje.<br />
                Aktualizacja starych sufiksów wymaga wcześniejszego ich skasowania.</p>

        <div class="row">
        <div class="col-sm">
                <form action="#" method="post">
                        {{ form.account|as_crispy_field }}
                    <input type="submit" class="btn btn-primary" value="Uzupełnij">
                    {% csrf_token %}
                </form>
        </div>
        <div class="col-sm">
        </div>
        <div class="col-sm">
        </div>
        </div>

{% endblock %}

templates/strategy.html
{% extends "__base__.html" %}
{% block title %}ROAS Manager | Edycja strategii{% endblock %}
{% load static %}
{% block content %}

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1>Edycja strategii</h1>
    </div>

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'strategies' %}">Strona główna</a></li>
            <li class="breadcrumb-item"><a href="{% url 'strategies' %}">Strategie</a></li>
            <li class="breadcrumb-item"><a href="{% url 'log' strategy.id %}">{{ strategy.name }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Edycja</li>
        </ol>
    </nav>

    <div class="row">
        <div class="col-sm">
            <form action="#" method="post" class="form-horizontal">
                <div class="form-group row">
                    <div class="col-sm-4">
                        <label>
                            {{ form.name.label}}
                            {{ form.name }}
                        </label>
                    </div>
                    <div class="col-sm">
                        <label>
                            Konto:
                            <select name="account" class="form-control" required id="id_account" disabled>
                                <option value="{{ strategy.account.id }}">{{ strategy.account.account_name }}</option>
                            </select>
                        </label>
                    </div>
                    <div class="col-sm">
                        <label>
                            Grupa kampanii{% if not strategy.campaign_group %}<b>**</b>{% endif %}:
                            <select name="campaign_group" class="form-control" required id="id_campaign_group">
                                {% for cg in campaign_groups %}
                                    {% if strategy.campaign_group == cg %}
                                        <option value="{{ cg.id }}" data-account_id="{{ cg.account.id }}" selected>{{ cg.name }}</option>
                                    {% else %}
                                        <option value="{{ cg.id }}" data-account_id="{{ cg.account.id }}">{{ cg.name }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </label>
                    </div>
                    <div class="col-sm">
                        <label>
                            Nr ID strategii:
                            <input type="number" value="{{ strategy.strategy_id }}" name="strategy_id" class="form-control" required disabled id="id_strategy_id">
                        </label>
                    </div>
                    <div class="col-sm">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm">
                        <div class="custom-control custom-switch">
                            {{ form.make_changes }}
                            <label for="id_make_changes" class="custom-control-label">Zarządzanie budżetem</label>
                        </div>
                    </div>
                </div>

                <button type="submit" class="btn btn-primary">Zapisz</button>
                {% csrf_token %}
            </form>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-sm">
            <h2>Przypisane budżety</h2>

            <div class="table-responsive">
                <table class="table table-striped table-sm">
                    <tr>
                        <th>Budżet</th>
                        <th>Grupa kampanii</th>
                        <th>Początek</th>
                        <th>Koniec</th>
                        <th>Edycja</th>
                    </tr>
                    {% for budget in budgets %}
                        <tr>
                            <td class="currency">{{ budget.to_spend }}</td>
                            <td>{{ budget.campaign_group }}</td>
                            <td>{{ budget.date_from|date:"d-m-Y" }}</td>
                            <td>{{ budget.date_to|date:"d-m-Y" }}</td>
                            <td><a href="{% url 'edit_budget' strategy.id budget.id %}">Edycja</a></td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    {% if strategy.campaign_group %}
        <div class="row mt-4">
            <div class="col-sm">
                <a class="align-items-center" href="{% url 'add_budget' strategy.campaign_group.id %}"><span data-feather="plus-circle"></span>  Dodaj budżet</a>
            </div>
        </div>
    {% else %}
        <div class="row mt-4">
            <div class="col-sm">
                <a class="align-items-center isDisabled" href=""><span data-feather="plus-circle"></span>  Dodaj budżet*</a>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-sm">

                <p><b>*</b>    aby przypisać budżet to tej strategii, najpierw przypisz ją do wybranej grupy kampanii (menu na górze strony).</p>
                <p><b>**</b> Jeżeli lista jest pusta, lub nie ma na niej właściwej grupy, należy wcześniej <a href="{% url 'add_campaign_group' %}">pobrać grupy kampanii </a> dla konta {{ strategy.account.account_name }}.</p>

            </div>
        </div>
    {% endif %}
{% endblock %}

{% block hide_checkboxes_js %}
    <script src="{% static 'js/hide_checkboxes.js' %}"></script>
{% endblock hide_checkboxes_js %}